version: "3.9"
services:
    clean:
        build: .
        volumes:
            - ~/dev/temp/backups:/var/destination
        environment:
            - SCHEDULE="0 0 3 * *"
            - INCLUDE_PATTERN="$$(date +%Y)*.sql.gz"
            - EXCLUDE_PATTERN="????????_09*.sql.gz"

