version: "3.3"
services:
  file-delete:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - $LOCAL_DESTINATION:/var/destination
    ports:
        - 127.0.0.1:18080:18080
    env_file: .env
